# Generated by Django 5.1 on 2024-08-27 15:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('eleve', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='eleves',
            name='age',
            field=models.PositiveIntegerField(default=22),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='eleves',
            name='classe',
            field=models.CharField(choices=[('Tle', 'Terminale'), ('1ere', 'Première'), ('2nd', 'Deuxième'), ('3eme', 'Troisième'), ('4eme', 'Quatrième'), ('5eme', 'Cinquième'), ('6eme', 'Sixième')], max_length=10),
        ),
        migrations.AlterField(
            model_name='eleves',
            name='date_de_creation',
            field=models.DateField(auto_now_add=True),
        ),
    ]
