# Generated by Django 5.1 on 2024-08-27 15:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('eleve', '0002_eleves_age_alter_eleves_classe_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='eleves',
            name='genre',
            field=models.CharField(choices=[('M', 'Masculin'), ('F', 'Féminin')], default=22, max_length=10),
            preserve_default=False,
        ),
    ]
