# Generated by Django 5.1.1 on 2024-09-08 12:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('student', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='studentmodel',
            name='genre',
            field=models.CharField(choices=[('F', 'WOMEN'), ('M', 'MEN'), ('O', 'OTHER')], max_length=50),
        ),
    ]
