# Generated by Django 5.1 on 2024-08-23 16:32

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Utilisateurs',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pseudo', models.CharField(max_length=10, unique=True)),
                ('mot_de_passe', models.CharField(max_length=128)),
                ('date_de_creation', models.DateField(auto_now_add=True)),
            ],
        ),
    ]
