# Generated by Django 5.1 on 2024-09-04 23:14

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('base', '0001_initial'),
        ('user', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='TeacherModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('status', models.BooleanField(default=True)),
                ('nom', models.CharField(max_length=50)),
                ('prenom', models.CharField(max_length=50)),
                ('date_de_creation', models.DateField(auto_now_add=True)),
                ('picture', models.URLField()),
                ('telephone', models.CharField(max_length=50)),
                ('genre', models.CharField(choices=[('F', 'Female'), ('M', 'Male'), ('O', 'Other')], max_length=50)),
                ('age', models.PositiveIntegerField()),
                ('vacant', models.CharField(choices=[('Oui', 'Oui'), ('Non', 'Non')], max_length=50)),
                ('matiere_enseigne', models.CharField(choices=[('Math', 'Math'), ('SVT', 'SVT'), ('Anglais', 'Anglais'), ('Physique', 'Physique'), ('EPS', 'EPS'), ('Philosophie', 'Philosophie'), ('Francais', 'Francais')], max_length=30)),
                ('adress', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='base.addressmodel')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='user.usermodel')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
