# Generated by Django 5.1 on 2024-08-27 15:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('professeurs', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='professeurs',
            name='date_de_creation',
            field=models.DateField(auto_now_add=True),
        ),
    ]
