# Generated by Django 5.1 on 2024-08-27 15:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('professeurs', '0002_alter_professeurs_date_de_creation'),
    ]

    operations = [
        migrations.AddField(
            model_name='professeurs',
            name='age',
            field=models.PositiveIntegerField(default=20),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='professeurs',
            name='matiere_enseigne',
            field=models.CharField(choices=[('Math', 'Terminale'), ('SVT', 'Première'), ('Anglais', 'Deuxième'), ('Physique', 'Troisième'), ('EPS', 'Quatrième'), ('Philosophie', 'Cinquième'), ('Francais', 'Sixième')], max_length=30),
        ),
        migrations.AlterField(
            model_name='professeurs',
            name='vacant',
            field=models.BooleanField(choices=[('Oui', 'Oui'), ('Non', 'Non')], max_length=50),
        ),
    ]
