# Generated by Django 5.1 on 2024-08-27 15:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('professeurs', '0003_professeurs_age_alter_professeurs_matiere_enseigne_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='professeurs',
            name='matiere_enseigne',
            field=models.CharField(choices=[('Math', 'Math'), ('SVT', 'SVT'), ('Anglais', 'Anglais'), ('Physique', 'Physique'), ('EPS', 'EPS'), ('Philosophie', 'Philosophie'), ('Francais', 'Francais')], max_length=30),
        ),
        migrations.AlterField(
            model_name='professeurs',
            name='vacant',
            field=models.CharField(choices=[('Oui', 'Oui'), ('Non', 'Non')], max_length=50),
        ),
    ]
