# Generated by Django 5.1.1 on 2024-09-09 09:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='usermodel',
            name='role',
        ),
        migrations.AddField(
            model_name='usermodel',
            name='role',
            field=models.ManyToManyField(to='user.roleusermodel'),
        ),
    ]
